[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-sqlite = "0.5.1"
dotenv = "0.15.0"
interface = {path="../interface/"}
thiserror = "2.0.12"
tokio = {version = "1.45.0", features=["full"]}
