[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
askama = "0.14.0"
actix-files = "0.6.6"
serde_json = "1.0.140"
serde = {version="1.0.219", features=["derive"]}
async-sqlite = "0.5.1"
polars = { version = "0.46.0" , features=["lazy", "strings"]}
